### PR TITLE
FIX: Fixed selector for python class.

### PR DESCRIPTION
**Pull request by amakhnach**

### CODE REVIEW

**Comment by pokidovea** [comment]
What does your PR fix? As I know this plugin works fine.

**Comment by amakhnach** [comment]
After latest Sublime3 update plugin started returning wrong value instead of class name.

I can reproduce localy like this:
I installed your current version of plugin and created simple python file `some_class.py`.
```
class SomeClass(object):

    def some_method(self):
        pass
```
After copying path to `some_method` I am getting `some_class.class.some_method` but with my fix I am getting `some_class.SomeClass.some_method`

**Comment by pokidovea** [comment]
I can't confirm this. I tried your example and plugin returned `some_class.SomeClass.some_method`.
I'll try your fix on my environment.
My version of Sublime is the same.

**Comment by pokidovea** [comment]
For python3 syntax (my default)
```
source.python.3
meta.class.python.3
entity.name.type.class.python.3
```
For python(Django) syntax
```
source.python.django
meta.class.python
entity.name.class.python
```
For python2 syntax
```
source.python
meta.class.python
entity.name.class.python
```
So, scope depends on syntax. If you fix your PR to take both scopes, I'll accept it.

**Comment by amakhnach** [comment]
Okay, np. I will make support for both cases.

**Comment by pleasedontbelong** [comment]
:+1: Had the same problem, this fixes the plugin for ST3

**Comment by alimony** [comment]
I know this is old, but will it be merged? Having the same problem.

**Pull request merged**
